$schema: "http://json-schema.org/draft-07/schema#"

description: seq2science single-cell atac-seq configuration

properties:
  snaptools_opt:
    description: TODO @JGASmits add description
    default: --min-flen=0 --max-flen=1000 --keep-single=FALSE --keep-secondary=FALSE --overwrite=True --min-cov=100 --verbose=True
  bin_opt:
    description: TODO @JGASmits add description
    default: --bin-size-list 5000 --verbose=True
